//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ciboAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedidos()
        {
            this.platillosPedidos = new HashSet<platillosPedidos>();
        }
    
        public int idPedido { get; set; }
        public int idDireccionCliente { get; set; }
        public int idDireccionRestaurante { get; set; }
        public int idRepartidor { get; set; }
        public Nullable<System.DateTime> fechaPedido { get; set; }
        public string comentarios { get; set; }
        public string estadoPedido { get; set; }
        public string estadoPago { get; set; }
        public Nullable<float> puntajeServicio { get; set; }
        public Nullable<float> comisionRepartidor { get; set; }
        public string metodoPago { get; set; }
        public string respuesta_Inconveniente_interno { get; set; }
    
        public virtual DireccionCliente DireccionCliente { get; set; }
        public virtual DireccionRestaurante DireccionRestaurante { get; set; }
        public virtual repartidor repartidor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<platillosPedidos> platillosPedidos { get; set; }
    }
}
