//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ciboAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class platillosPedidos
    {
        public int id_platillosPedidos { get; set; }
        public Nullable<int> idPedido { get; set; }
        public Nullable<int> id_Platillo { get; set; }
        public Nullable<int> cant { get; set; }
        public Nullable<float> precio { get; set; }
        public string sizeDescripcion { get; set; }
    
        public virtual pedidos pedidos { get; set; }
        public virtual platillos platillos { get; set; }
    }
}
