//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ciboAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class platillos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public platillos()
        {
            this.PlatilloSize = new HashSet<PlatilloSize>();
            this.platillosPedidos = new HashSet<platillosPedidos>();
        }
    
        public int id_Platillo { get; set; }
        public int idImagen { get; set; }
        public int id_CategoriasProductos { get; set; }
        public string nombre { get; set; }
        public string descp { get; set; }
        public float precio { get; set; }
        public int tiempoMinutosMax { get; set; }
        public bool hasSize { get; set; }
        public bool isActive { get; set; }
    
        public virtual CategoriasProductos CategoriasProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatilloSize> PlatilloSize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<platillosPedidos> platillosPedidos { get; set; }
    }
}
