//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ciboAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatilloSize
    {
        public int id_platillo_size { get; set; }
        public string sizeDesc { get; set; }
        public string DescripcionExtra { get; set; }
        public float precio { get; set; }
        public int id_Platillo { get; set; }
    
        public virtual platillos platillos { get; set; }
    }
}
