//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ciboAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetirosRepartidor
    {
        public int idRetirosRepartidor { get; set; }
        public System.DateTime fechaCobro { get; set; }
        public float cantidadCobrada { get; set; }
        public int idRepartidor { get; set; }
    
        public virtual repartidor repartidor { get; set; }
    }
}
